// Generated by scripts/generate-custom-domain.mjs. Do not edit.
const HOST = new RegExp("^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$");
const MAXIMUM_HOSTNAME_LENGTH = 63;
const FORBIDDEN_PREFIXES = ["www.www."];
const FORBIDDEN_SUFFIXES = [".github.io"];
const MESSAGE = {
  "empty": "Enter a domain such as blog.example.com.",
  "components": "Enter only the hostname, without a protocol, path, port or credentials.",
  "policy": "Enter a valid custom hostname shorter than 64 characters and outside github.io.",
  "labels": "Enter a complete domain with valid DNS labels.",
  "invalid": "Enter a valid domain such as blog.example.com."
};

export function customDomain(value) {
  const source = typeof value === 'string' ? value.trim().toLowerCase().replace(/\.$/, '') : '';
  if (!source) return { error: MESSAGE.empty };
  try {
    const parsed = new URL(`https://${source}`);
    if (parsed.username || parsed.password || parsed.port || parsed.pathname !== '/'
        || parsed.search || parsed.hash || parsed.hostname !== source) {
      return { error: MESSAGE.components };
    }
    if (source.length > MAXIMUM_HOSTNAME_LENGTH
        || FORBIDDEN_PREFIXES.some((prefix) => source.startsWith(prefix))
        || FORBIDDEN_SUFFIXES.some((suffix) => source.endsWith(suffix))) {
      return { error: MESSAGE.policy };
    }
    if (!HOST.test(source)) return { error: MESSAGE.labels };
    return { host: source };
  } catch {
    return { error: MESSAGE.invalid };
  }
}
